version: "3.5"

services:
  redis:
    build: 
      context: redis
      dockerfile: Dockerfile
    container_name: redislocal
    hostname: redislocal
    ports:
      - 6379:6379
    network_mode: host
    volumes:
      - local_redis_data:/data

volumes:
  local_redis_data: