version: 2.1   

jobs:
  build:
    docker:
      - image: conanio/gcc11
    steps:
      - checkout
      - run:
          name: "install building tools"
          command: |
            sudo pip install --upgrade conan 
            conan config set general.revisions_enabled=1
            conan profile new --detect --force default 
            conan profile update settings.compiler.libcxx=libstdc++11 default
      - run:
          name: "build the code"
          command: |
            mkdir -p build && cd build
            conan install ..
            cmake ..
            make -j 10

      - persist_to_workspace:
          root: .
          paths: 
           - build

  test:
    docker:
      - image: conanio/gcc11
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build
      - run:
          name: Start all services declared in docker-compose.yml
          command: docker-compose up -d
      - run:
          name: "run the test"
          command: |
            cd build/test
            ./redis_time_series_test
      - store_test_results:
          path: build

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
