version: 2.1   

jobs:
  build:
    docker:
      - image: conanio/gcc11
    steps:
      - checkout
      - run:
          name: "install building tools"
          command: |
            sudo pip install --upgrade conan 
            conan config set general.revisions_enabled=1
            conan profile new --detect --force default 
            conan profile update settings.compiler.libcxx=libstdc++11 default
            conan profile update settings.compiler.version=10 default
      - run:
          name: "build the code"
          command: |
            mkdir -p build && cd build
            conan install ..
            cmake ..
            make -j 10
      - persist_to_workspace:
          root: .
          paths: 
           - build/test
           - redis
           - docker-compose.yml

  test:
    docker:
      # - image: conanio/gcc11
      - image: cimg/base:stable
        auth:
          username: nasirim
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - attach_workspace:
          at: .
      - run:
          name: run redis
          command: |
            sudo apt update
            wget http://download.redis.io/redis-stable.tar.gz
            tar xvzf redis-stable.tar.gz
            cd redis-stable
            make
            sudo make install
            cd ..
            sudo chmod +x redis/redistimeseries.so
            redis-server "redis/redis.conf" > /tmp/redis.log 2>&1 &
            sleep 15
            cat /tmp/redis.log
      - run:
          name: "run the test"
          command: |
            ./build/test/redis_time_series_test
      - store_test_results:
          path: build/test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
