version: 2.1   

jobs:
  build:
    docker:
      - image: conanio/gcc11
    steps:
      - checkout
      - run:
          name: "install building tools"
          command: |
            sudo pip install --upgrade conan 
            conan config set general.revisions_enabled=1
            conan profile new --detect --force default 
            conan profile update settings.compiler.libcxx=libstdc++11 default
            conan profile update settings.compiler.version=10 default
      - restore_cache:
          keys:
            - conan-cache-v1-{{ checksum "conanfile.txt" }}
            - conan-cache-v1
      - run:
          name: "Install conan packages"
          command: |
            mkdir -p build && cd build
            conan install ..
      - save_cache:
          key: conan-cache-v1-{{ checksum "conanfile.txt" }}
          paths:
            - ~/.conan
      - run:
          name: "build the code"
          command: |
            mkdir -p build && cd build
            conan install ..
            cmake ..
            make -j 10
      - persist_to_workspace:
          root: .
          paths: 
           - build/test
           - redis/redis*
  test:
    docker:
      - image: cimg/base:stable
        auth:
          username: nasirim
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "download redis"
          command: |
            wget http://download.redis.io/redis-stable.tar.gz
      - restore_cache:
          keys:
            - v1-make-redis-{{checksum "redis-stable.tar.gz"}}
            - v1-make-redis-
      - run:
          name: "make redis"
          command: |
            tar xvzf redis-stable.tar.gz
            cd redis-stable
            make
      - save_cache:
          key: v1-make-redis-{{checksum "redis-stable.tar.gz"}}
          paths:
            - redis-stable
      - run:
          name: "run redis server"
          command: |
            chmod +x redis/redistimeseries.so
            ./redis-stable/src/redis-server "redis/redis.conf" > /tmp/redis.log 2>&1 &
            sleep 10
            cat /tmp/redis.log
      - run:
          name: "run the test"
          command: |
            ./build/test/redis_time_series_test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
