version: 2.1   

jobs:
  build:
    docker:
      - image: conanio/gcc11
    steps:
      - checkout
      - run:
          name: "install building tools"
          command: |
            sudo pip install --upgrade conan 
            conan config set general.revisions_enabled=1
            conan profile new --detect --force default 
            conan profile update settings.compiler.libcxx=libstdc++11 default
            conan profile update settings.compiler.version=10 default
      - run:
          name: "build the code"
          command: |
            mkdir -p build && cd build
            conan install ..
            cmake ..
            make -j 10
      - persist_to_workspace:
          root: .
          paths: 
           - build/test
           - redis
           - docker-compose.yml

  test:
    docker:
      # - image: conanio/gcc11
      - image: cimg/base:stable
        auth:
          username: nasirim
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build
      - run:
          name: Start all services declared in docker-compose.yml
          command: docker-compose up -d 
      - run:
          command: |
            sleep 10
            ss -tulw

      - run:
          name: "run the test"
          command: |
            sleep 10
            ./build/test/redis_time_series_test
      - store_test_results:
          path: build/test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
